### ISSUE TITLE
[bug] 在同一个模块中第三次调用 op 时发生异常

### ISSUE THREAD

**Issue by Snoopy1866** [gaogaotiantian/objprint#112]
- 系统版本：Windows 10 22H2 19045.5011
- Python 版本：Python 3.13.0 (tags/v3.13.0:60403a5, Oct  7 2024, 09:38:07) [MSC v.1941 64 bit (AMD64)] on win32
- objprint 版本：0.2.3

以下代码可以正常执行：

```python
from objprint import op


class Person:
    def __init__(self, sex: str, age: int) -> None:
        self.sex = sex
        self.age = age


a = Person("A", 18)
op(a)

b = Person("B", 20)
op(b)
```

以下代码会抛出 `AssertionError` 异常：

```python
from objprint import op


class Person:
    def __init__(self, sex: str, age: int) -> None:
        self.sex = sex
        self.age = age


a = Person("A", 18)
op(a)

b = Person("B", 20)
op(b)

c = Person("C", 22)
op(c)
```

Traceback 输出：

```cmd
Traceback (most recent call last):
  File "c:\Users\wtwang\Desktop\Untitled-1.py", line 11, in <module>
    op(a)
    ~~^^^
  File "C:\Users\wtwang\AppData\Local\Programs\Python\Python313\Lib\site-packages\objprint\objprint.py", line 121, in __call__
    if self.frame_analyzer.return_object(call_frame):
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\wtwang\AppData\Local\Programs\Python\Python313\Lib\site-packages\objprint\frame_analyzer.py", line 74, in return_object  
    node: Optional[ast.AST] = Source.executing(frame).node
                              ~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\wtwang\AppData\Local\Programs\Python\Python313\Lib\site-packages\objprint\executing\executing.py", line 378, in executing
    assert_(new_stmts <= stmts)
    ~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wtwang\AppData\Local\Programs\Python\Python313\Lib\site-packages\objprint\executing\executing.py", line 154, in assert_  
    raise AssertionError(str(message))
AssertionError
```

此时，如再次执行下面的代码（与上述第一段代码一致）：

```python
from objprint import op


class Person:
    def __init__(self, sex: str, age: int) -> None:
        self.sex = sex
        self.age = age


a = Person("A", 18)
op(a)

b = Person("B", 20)
op(b)
```

则会发生异常：

```cmd
Traceback (most recent call last):
  File "c:\Users\wtwang\Desktop\Untitled-1.py", line 11, in <module>
    op(a)
    ~~^^^
  File "C:\Users\wtwang\AppData\Local\Programs\Python\Python313\Lib\site-packages\objprint\objprint.py", line 121, in __call__
    if self.frame_analyzer.return_object(call_frame):
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "C:\Users\wtwang\AppData\Local\Programs\Python\Python313\Lib\site-packages\objprint\frame_analyzer.py", line 74, in return_object  
    node: Optional[ast.AST] = Source.executing(frame).node
                              ~~~~~~~~~~~~~~~~^^^^^^^
  File "C:\Users\wtwang\AppData\Local\Programs\Python\Python313\Lib\site-packages\objprint\executing\executing.py", line 378, in executing
    assert_(new_stmts <= stmts)
    ~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wtwang\AppData\Local\Programs\Python\Python313\Lib\site-packages\objprint\executing\executing.py", line 154, in assert_
    raise AssertionError(str(message))
AssertionError
```

**Comment by gaogaotiantian** [comment]
这是老版本的executing不支持3.13，我这两天把executing更新一下版本。
